default_language_version:
    python: python3.8
exclude: ^pending_rebuild/
ci:
    skip:
        - black-local
        - mypy-local
        - pylint-local
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v3.4.0'
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: fix-encoding-pragma
    -   id: check-docstring-first
    -   id: check-json
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
    -   id: bandit
        args: [--skip, "B101,B309"]
-   repo: local
    hooks:
    -   id: black-local
        name: black
        entry: black
        language: system
        types: [python]
    -   id: pylint-local
        name: pylint
        entry: pylint
        language: system
        types: [python]
    -   id: mypy-local
        name: mypy
        entry: mypy
        language: system
        types: [python]
