language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --upgrade pip setuptools wheel
  - pip install .
# command to run tests
script: python -m unittest discover -s tests